Allow no `--use-database` when `--just-client`
This is the second part of fixing #510, the error when `--use-database`
is missing looks like:

```
[ketrew: ERROR]
    Error: Cannot configure a full blown Ketrew without the
    `--use-database` option;
    Please use a database URI or configure just a client with
    `--just-client`
```