Make `ketrew start-server` report errors
This is a fix for #252, the `System.sleep 2.` could be improved upon in
the future; it may also require tweaking the actual value.

With a server configured on a root-only port:

     $ kddaemon start
    [ketrew] Started the daemon, now waiting for the server
    status.
    [ketrew] The server seems to have failed to start
    (connection refused).
    [ketrew]
        Here is the latest start-error:
    2015-11-24-22h54m18s032ms-UTC (PID: 52689)
    Error starting the server: Unix.Unix_error(Unix.EACCES, "bind", "")

the “old” behavior is still available with the `--no-status` option:

     $ kddaemon start --no-status
    <silently returns immediately>

there is also a `Printf.eprintf` to be sure the error is seen when not
daemonizing:

     $ kdserver start
    ERROR: Starting the server failed:
    2015-11-24-22h54m38s015ms-UTC (PID: 52778)
    Error starting the server: Unix.Unix_error(Unix.EACCES, "bind", "")